### ISSUE TITLE
todo: some minor ux fix

### ISSUE THREAD

**Issue by RetricSu** [RetricSu/godwoken-kicker#31]
- [x] web3 should get started after godwoken rpc server established instead of checking the config.toml file exists. 
- [x] better env file workflow (manual build list shoud detached with submodule list file)
- [x] better docs on how to set up custom setting in manual-mode
- [x] web3 should build godwoken js file in docker-prebuild-image
- [x] reduce time installing node_module for web3 and examples these two js project in init stage.
- [x] show commit time in manual.build.list.env file when generating
- [x] better componet version description
- [x] extract used image variable to support easy update submodule in prebuild-mode
- [x] maybe quick-mode should also be able to pick the version he/she wants?
- [x] example findCreatorId failed right after gw-rpc server up
- [x] merge edit_godwoken_config.sh file into gw_util.sh
- [x] refactor the process of prepare scripts and bin used for deploy godwoken chain, make it more simple and clear
